import {Entity,PrimaryGeneratedColumn,Column,ManyToOne,JoinColumn,Index,} from 'typeorm';
import { Ventas } from 'src/ventas/ventas.entity';
import { Producto } from 'src/producto/producto.entity';

/**
 * Entity representing the many-to-many relationship between sales and products.
 * Acts as a junction table that stores sale details (quantity, price, subtotal).
 * Enforces uniquesess: a product can apper only once per sale 
 */

@Index(['venta', 'producto'], { unique: true })
@Entity('venta_producto')
export class VentaProducto {
  
  /**
   * Unique identifier for the sale-product record, auto-generated by the database.
   */
  @PrimaryGeneratedColumn()
  id_venta_producto!: number;

  /**
   * Quantity of the product included in the sale.
   */
  @Column({ type: 'int' })
  cantidad!: number;

/**
 * unit price of the product at the time of sale.
 * Stored as a decimal with up to 10 digits and 2 decimal places. 
 */
  @Column({ type: 'decimal', precision: 10, scale: 2 })
  precio_unitario!: number;

/**
 * Subtotal for this product in the sale (quantity x unit price).
 * stored as a decimal with up to 10 digits and 2 decimnal places.
 */
  @Column({ type: 'decimal', precision: 10, scale: 2 })
  subtotal!: number;

  /**
   * Many-to-one relationship with the Ventas(sale) entity.
   * Each sale-product record belong to one sale.
   * Cascades delete and update operations from the parent sale.
   */
  // Relación con Ventas
  @ManyToOne(() => Ventas, (venta) => venta.ventaProductos, {
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE', 
  })
  @JoinColumn({ name: 'id_venta' })
  venta!: Ventas;

  /**
   * Many-to-one realationship with the productos(product) entity.
   * Each sale-product record references one product.
   * Cascades delete  and update operations from the parent product.
   */
  // Relación con Producto
  @ManyToOne(() => Producto, (producto) => producto.ventaProductos, {
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE', 
  })
  @JoinColumn({ name: 'id_producto' })
  producto!: Producto;
}
