import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, OneToMany } from 'typeorm';
import { Proveedor } from '../proveedor/proveedor.entity';
import { Categoria } from 'src/categoria/categoria.entity';
import { VentaProducto } from 'src/venta_producto/venta_producto.entity'; // Importa la entidad
/**
 * Entity representing a product in the database 
 * Contains product  details and realtionship with supplier, category, and sales.
 */

@Entity('producto')
export class Producto {
  /**
   * Unique identifier for the product, auto-generated by the database.
   */
  @PrimaryGeneratedColumn()
  id_producto: number;

  /**
   * Name of the product.
   */
  @Column()
  nombre: string;

  /**
   * Detailed description of the product.
   */
  @Column()
  descripcion: string;

  /**
   * Price of the product. Stored as a decimal value.
   */
  @Column('decimal')
  precio: number;

  /**
   * Current stock quality of the product.
   */
  @Column('int')
  stock: number;

  /**
   * Many-to-one relationship with the Proveedor (supplier) entity.
   * Each product belong to one supplier.
   */
  // Relaciones existentes
  @ManyToOne(() => Proveedor, (proveedor) => proveedor.productos)
  proveedor: Proveedor;

  /**
   * Many-to-one relationship with the Categoria (Category) entity.
   * Each product belong to one category.
   */
  @ManyToOne(() => Categoria, (categoria) => categoria.productos)
  categoria: Categoria;

/**
 * One-to-many relationship with the VentaProducto (sale-product)entity.
 * A product can apper in multiple sale records.
 */
  //RELACIÓN CON VENTA_PRODUCTO
  @OneToMany(() => VentaProducto, (ventaProducto) => ventaProducto.producto)
  ventaProductos: VentaProducto[];
}