import { Entity, PrimaryGeneratedColumn, Column, OneToMany, UpdateDateColumn, DeleteDateColumn } from 'typeorm';
import { Ventas } from 'src/ventas/ventas.entity'; 
import { Facturacion } from 'src/facturacion/facturacion.entity'; 

/**
 * Entity representing a user in the system.
 * Supports soft deletion and tracks modification timestamps
 */
@Entity('usuario')
export class Usuario {

  /**
   * Unique identifier for the user, auto-generated by the database.
   */
  // define la columna de id de usuario como clave primaria
  @PrimaryGeneratedColumn()
  id_usuario: number;

  /**
   * Full name of the user, up to 100 characters.
   */
  @Column({ length: 100 }) // define el tamaño máximo de 100 caracteres para el nombre
  nombre: string;

  /**
   * Email address of the user, must be unique across the system.
   * Used for login and communication.
   */
  @Column({ unique: true, length: 150 }) // unique asegura que no hay dos usuarios con el mismo correo
  correo: string;

  /**
   * Hashed password of the user (never stored in plain text).
   * Generated using bcrypt during registration or password update.
   */
  @Column({ length: 200 }) // alamacena el hash de la contraseña
  contrasena: string;

  /**
   * Role of the user in the system (e.g., 'admin', 'empleado').
   * Defaults to 'empleado' if not specified.
   */
  @Column({ default: 'empleado' }) // columna rol con un valor por defecto
  rol: string;

  /**
   * One-to-many relationship with the Ventas (sales) entity.
   * A user can be associated with multiple sales.
   */
  // Relaciones
  @OneToMany(() => Ventas, (venta) => venta.usuario, { nullable: true })
  ventas?: Ventas[];
  // RELACIÓN UNO A MUCHOS: Un Usuario puede tener MUCHAS Ventas.
   // 1. () => Ventas: Define la entidad relacionada.
   // 2. (venta) => venta.usuario: Define la propiedad en la entidad Ventas que mapea de vuelta a Usuario.
   // 3. nullable: true: Indica que, aunque una venta requiere un usuario, el lado del array puede estar vacío.
   //'ventas?: Ventas[]' es la propiedad que contendrá el array de ventas si se carga la relación.
   

   /**
   * One-to-many relationship with the Facturacion (invoices) entity.
   * A user can be associated with multiple invoices.
   */
  @OneToMany(() => Facturacion, (factura) => factura.usuario, { nullable: true })
  facturas?: Facturacion[]; // indican que es un array de entidades opcional

  /**
   * Automatically updated timestamp indicating the last modification of the user record.
   */
  @UpdateDateColumn()
  updatedAt: Date;

  /**
   * Timestamp indicating when the user was soft-deleted.
   * If null, the user is active; if set, the user is considered deleted.
   */
  @DeleteDateColumn()
  deletedAt: Date;
}