// facturacion.entity.ts
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  OneToOne,
  JoinColumn,
} from 'typeorm';
import { Usuario } from 'src/usuario/usuario.entity';
import { Ventas } from 'src/ventas/ventas.entity';

/**
 * Entity representing an invoice in the database.
 * Contains billing details and relationship with sales and users.
 */
@Entity('facturacion')
export class Facturacion {
  /**
   * Unique identifier for the invoice, auto-generated by the database.
   */
  @PrimaryGeneratedColumn()
  id_facturacion: number;

  /**
   * Date an time when the invoice was issued, automatically set on cration.
   */
  @CreateDateColumn()
  fecha_emision: Date;

  /**
   * Total amount of the invoice, stored as a decimal with up to 10 digits and 2 decimal places.
   */
  @Column({ type: 'decimal', precision: 10, scale: 2 })
  total: number;

  /**
   * One - to - one relationship  with the Ventas (sales) entity
   */
  // 🔹 Esta relación es la DUEÑA del OneToOne
 @OneToOne(() => Ventas, (venta) => venta.facturacion, {
  onDelete: 'CASCADE',
  onUpdate: 'CASCADE',
})
@JoinColumn({ name: 'id_venta' }) // Este lado mantiene la FK
venta: Ventas;

/**
 * Many - to - one relationship with the Usuario (user) entity.
 * An invoice belongs to one user; a  user can have multiple invoices.
 * The foreign key (id_usuario) can be null.
 */
  @ManyToOne(() => Usuario, (usuario) => usuario.facturas, {
    onDelete: 'SET NULL',
    nullable: true,
  })
  @JoinColumn({ name: 'id_usuario' })
  usuario: Usuario;
}