import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  OneToOne,
  OneToMany,
  JoinColumn,
} from 'typeorm';
import { Usuario } from 'src/usuario/usuario.entity';
import { Facturacion } from 'src/facturacion/facturacion.entity';
import { VentaProducto } from 'src/venta_producto/venta_producto.entity'; // ✅ relación con la tabla intermedia


/**
 * Entity representing a sale in the system.
 * Contains sale details and relationship with user, invoice, and prducts.
 */
@Entity('ventas')
export class Ventas {

  /**
   * Unique identifier for the sale, auto-generated by the database.
   */
  // 🆔 Identificador único
  @PrimaryGeneratedColumn()
  id_venta: number;

  /**
   * Date and time when the sale was created, automatically set by the database.
   */
  // 📅 Fecha automática de creación
  @CreateDateColumn({ type: 'timestamp' })
  fecha: Date;

  /**
   * Total amount of the sale, stored as a decimal with up to 10 digits and 2 decimal places.
   */
  // 💰 Total de la venta
  @Column({ type: 'decimal', precision: 10, scale: 2 })
  total: number;

  /**
   * Many-to-one relationship with Usuario (User) entity.
   * Each sale belongs to one user. The  user is eagerly loaded with the sale.
   */
  // 👤 Relación: muchas ventas pertenecen a un usuario
  @ManyToOne(() => Usuario, (usuario) => usuario.ventas, {
    onDelete: 'CASCADE',
    eager: true, // carga automática del usuario
  })
  @JoinColumn({ name: 'id_usuario' })
  usuario: Usuario;

  /**
   * One-to-one relationship with the Facturacion (invoice) entity.
   * Each sale has exactly one associated invoice. Cascades save. update, and delete operations.
   */
  // 🧾 Relación 1:1 con facturación
@OneToOne(() => Facturacion, (factura) => factura.venta, {
  cascade: true,
  onDelete: 'CASCADE',
  onUpdate: 'CASCADE',
})
facturacion: Facturacion;

/**
 * One-to-many relationship with the VentaProducto (Sale-product)entity.
 * A sale can include multiple products. Cascades save operations.
 */
  // 🧩 Relación con venta_producto (una venta puede tener muchos productos)
  @OneToMany(() => VentaProducto, (vp) => vp.venta, {
    cascade: true,
  })
  ventaProductos: VentaProducto[];
}