// // Importamos los decoradores y tipos necesarios de TypeORM
// // Estos sirven para definir cómo se comportan las clases con la base de datos
import { Entity, PrimaryGeneratedColumn, Column, OneToMany } from 'typeorm';

// // Importamos la entidad Producto (para definir la relación entre ambas tablas)
import { Producto } from '../producto/producto.entity';

// // Indica que esta clase representa una tabla llamada "categoria" en la base de datos
/**
 * Entity representing  a product category in the database.
 * Each category can have multiple products (one - to - many relationship).
 */
@Entity('categoria')
export class Categoria {
/**
 * Unique identifier for the category, auto-generated by the database.
 */
 // Columna ID autogenerada (llave primaria)
@PrimaryGeneratedColumn()
id_categoria!: number;

/**
 * Name of the caregory, required, up to 100 characters.
 */
// Columna tipo texto con máximo 100 caracteres (nombre de la categoría)
@Column({ length: 100 })
nombre!: string;
/**
 * Optional description of the category, stored as long text.
 */
//   // Columna tipo texto largo (opcional, puede quedar vacía)
 @Column({ type: 'text', nullable: true })
descripcion?: string;

/**
 * One - to - many relationship with the Producto entity.
 * A category can have multiple products.
 */
//   // Relación uno a muchos (1 categoría tiene muchos productos)
//   // El primer argumento indica con qué entidad se relaciona
//   // El segundo define la propiedad inversa en la entidad Producto
@OneToMany(() => Producto, producto => producto.categoria)
productos!: Producto[];
}

